# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('advice_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('advice_content', models.CharField(blank=True, max_length=255, null=True)),
                ('advice_created', models.DateTimeField(blank=True, null=True)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'advice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionDetail',
            fields=[
                ('commission_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('commission_desc', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'commission_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionOrder',
            fields=[
                ('commission_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('commission_price', models.FloatField(blank=True, null=True)),
                ('commission_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_created', models.DateTimeField(blank=True, null=True)),
                ('commission_sent', models.DateTimeField(blank=True, null=True)),
                ('commission_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'commission_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbMemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=1)),
                ('status_desc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_member_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=10)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('delegation_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delegation_info', models.CharField(blank=True, max_length=500, null=True)),
                ('bind_phone', models.CharField(max_length=20)),
                ('weixin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=50)),
                ('card_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('status_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('status_desc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'member_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('message_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_rank', models.BigIntegerField(blank=True, null=True)),
                ('order_price', models.FloatField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=1, null=True)),
                ('order_created', models.DateTimeField(blank=True, null=True)),
                ('order_finished', models.DateTimeField(blank=True, null=True)),
                ('order_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('express_name', models.CharField(blank=True, max_length=20, null=True)),
                ('express_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'order_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20)),
                ('service_pwd', models.CharField(blank=True, max_length=500, null=True)),
                ('service_area', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('bank', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'service_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_content', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'short_message',
                'managed': False,
            },
        ),
    ]
