# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('advice_id', models.AutoField(primary_key=True, serialize=False)),
                ('advice_content', models.CharField(blank=True, max_length=255, null=True)),
                ('advice_created', models.DateTimeField(blank=True, null=True)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionDetail',
            fields=[
                ('commission_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('commission_desc', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionOrder',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_price', models.FloatField(blank=True, null=True)),
                ('commission_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_created', models.DateTimeField(blank=True, null=True)),
                ('commission_sent', models.DateTimeField(blank=True, null=True)),
                ('commission_status', models.CharField(blank=True, max_length=1, null=True)),
                ('commission_type', models.ForeignKey(db_column='commission_type', on_delete=django.db.models.deletion.DO_NOTHING, to='db.CommissionDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=10)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('delegation_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delegation_info', models.CharField(blank=True, max_length=100, null=True)),
                ('bind_phone', models.CharField(max_length=20)),
                ('weixin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=50)),
                ('card_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=1)),
                ('status_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('message_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('order_rank', models.BigIntegerField(blank=True, null=True)),
                ('order_price', models.FloatField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=1, null=True)),
                ('order_created', models.DateTimeField(blank=True, null=True)),
                ('order_finished', models.DateTimeField(blank=True, null=True)),
                ('order_memo', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, max_length=5, null=True)),
                ('express_name', models.CharField(blank=True, max_length=20, null=True)),
                ('express_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20)),
                ('service_pwd', models.CharField(blank=True, max_length=32, null=True)),
                ('service_area', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('bank', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ShortMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.MemberStatus'),
        ),
        migrations.AddField(
            model_name='commissionorder',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.Member'),
        ),
        migrations.AddField(
            model_name='advice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Service'),
        ),
        migrations.AddField(
            model_name='advice',
            name='user_name',
            field=models.ForeignKey(blank=True, db_column='user_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Member'),
        ),
    ]
