from django.conf.urls import url,include
from django.contrib import admin
import views

urlpatterns = [
    url(r'^DashBoard/$', views.DashBoard),
    url(r'^NoticeList/$', views.NoticeList),
    url(r'^MsgList/$', views.MsgList),
    url(r'^MsgList/ViewMsg/$', views.ViewMsg),
    url(r'^MsgList/ViewMsg/MsgRead/$', views.MsgRead),
    url(r'^MemberEdit/$', views.MemberEdit),
    url(r'^MemberEdit1/$', views.MemberEdit1),
    url(r'^MemberEdit/MemberSave/$', views.MemberSave),
    url(r'^MemberEdit1/MemberSave1/$', views.MemberSave1),
    url(r'^MemberEdit/MemberList/$', views.MemberList),
    url(r'^MemberList/$', views.MemberList),
    url(r'^MemberList/ViewMember/$', views.ViewMember),
    url(r'^MemberList/ViewMemberSelf/$', views.ViewMemberSelf),
    url(r'^MemberList/ViewReCome/$', views.ViewReCome),
    url(r'^MemberList/SetAudit/$', views.SetAudit),
    url(r'^MemberList/SetAudit1/$', views.SetAudit1),
    url(r'^MemberList/MemberEdit/$', views.MemberEdit),
    url(r'^MemberOrder/$', views.MemberOrder),
    url(r'^MemberOrder/Deliver/$', views.Deliver),
    url(r'^MemberOrder/Deliver/DeliverSub/$', views.DeliverSub),
    url(r'^UserMap/$', views.UserMap),
    url(r'^ComBank/$', views.ComBank),
    url(r'^Promotion/$', views.Promotion),
    url(r'^Promotion/MoneyAudit/$', views.MoneyAudit),
    url(r'^Promotion/MoneySub/$', views.MoneySub),
    url(r'^AdviceList/$', views.AdviceList),
    url(r'^AdviceList/AdviceView/$', views.AdviceView),
    url(r'^AdviceList/AdviceView/AdviceSub/$', views.AdviceSub),
    url(r'^SubService/$', views.SubService),
]
